In [1]:
import numpy as np

In [2]:
array1 = np.array([1, 2, 3])

array2 = np.array([[1], [2], [3]])
print(array1 + array2)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


Broadcasting only works with compatible arrays. NumPy compares a set of array dimensions from right to left.

Every set of dimensions must be compatible with the arrays to be broadcastable. A set of dimension lengths is compatible when

* one of them has a length of 1 or
* they are equal
Let's see an example.

array1 = shape(6, 7)
array2 = shape(6, 1)
Here, array1 and array2 are arrays with different dimensions (6,7) and (6,1) respectively.

The dimension length 7 and 1 are compatible because one of them is 1.

Similarly, 6 and 6 are compatible since they are the same.

As both sets of dimensions are compatible, the arrays are broadcastable.
