In [1]:
import numpy as np

# NumPy save() Function

In [5]:
array1 = np.array([[1,2,3],[4,5,6]])

# save the array to a file
np.save('file1.npy',array1)

# NumPy load() Function

In [6]:
# load the saved NumPy array
loaded_array = np.load('file1.npy')

# display the loaded array
print(loaded_array)

[[1 2 3]
 [4 5 6]]


# NumPy savetxt() Function

In [7]:
array2 = np.array([[1, 3, 5],[7, 9, 11]])

# save the array to a file
np.savetxt('file2.txt',array2)


# NumPy loadtxt() Function

In [8]:
print(np.loadtxt('file2.txt'))

[[ 1.  3.  5.]
 [ 7.  9. 11.]]
