In [1]:
import numpy as np

# Create Array Using Python List

In [ ]:
# Create a list named list1
list1 = [2,4,6,8]
# create numpy array using list1
array1 = np.array(list1)

print(array1)

array2 = np.array([5,6,7,10])
print(array2)

[2 4 6 8]
[ 5  6  7 10]


# Create an Array Using np.zeros() and np.ones()

In [ ]:
# create an array with 4 elements filled with zeros
array3 = np.zeros(4)
print(array3)

# create an array with 4 elements filled with ones
array4 = np.ones(5)
print(array4)

[0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


# Create an Array With np.arange()

In [ ]:
# create an array with values from 0 to 4
array5 = np.arange(5)
print(array5)

[0 1 2 3 4]


# Create an Array With np.random.rand()

In [ ]:
# generate an array of 5 random numbers
array6 = np.random.rand(5)
print(array6)

[0.2829593  0.14559709 0.91453466 0.62221149 0.29971873]


# Create an Empty NumPy Array

In [ ]:
# create an empty array of length 4
array7 = np.empty(4)
print(array7)

[0. 0. 0. 0.]
