In [1]:
import numpy as np

# Create a 2-D NumPy Array


In [ ]:
# create a 2D array with 2 rows and 4 columns
array1 = np.array([[1,2,3,4],[5,6,7,8,]])
print(array1)

[[1 2 3 4]
 [5 6 7 8]]


# Create a 3-D NumPy Array

In [3]:
# create a 3D array with 2 "slices", each of 3 rows and 4 columns
array2 = np.array([[[1, 2, 3, 4],
                [5, 6, 7, 8], 
                [9, 10, 11, 12]],
                     
                [[13, 14, 15, 16], 
                 [17, 18, 19, 20], 
                 [21, 22, 23, 24]]])

print(array2)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


# Create N-D Arrays using np.zeros()

In [6]:
# create 2D array with 2 rows and 3 columns filled with zeros
array3 = np.zeros((2,3))
print(array3)

# create 3D array with 2 rows and 3 columns filled with zeros
array4 = np.zeros((2,3,4))
print(array4)

[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


# Create N-D Array with a Specified Value

In [7]:
# Create a 2-D array with elements initialized to 5 
array5 = np.full((2,2),5)
print(array5)

[[5 5]
 [5 5]]


# Creating Arrays With np.random.rand()

In [10]:
# Create a 2D array of 2 rows and 2 columns of random numbers
array6 = np.random.rand(2,2)
print(array6)

# create a 3D array of shape (2, 2, 2) of random numbers
array7 = np.random.rand(2, 2, 2)
print("\n3-D array: ")
print(array7)

[[0.85895052 0.33384899]
 [0.12089839 0.88761697]]

3-D array: 
[[[0.86247725 0.84965179]
  [0.3768684  0.52605477]]

 [[0.82639935 0.0064576 ]
  [0.78170894 0.97146981]]]


# Create Empty N-D NumPy Array

In [11]:
# create an empty 2D array with 2 rows and 2 columns
array8 = np.empty((2,2))
print(array8)

[[0.85895052 0.33384899]
 [0.12089839 0.88761697]]


We used the np.empty() function to create an empty 2-D array and a 3-D array respectively.

If we look into the output of the code, we can see the empty array is actually not empty, it has some values in it.

It is because although we are creating an empty array, NumPy will try to add some value to it. The values stored in the array are arbitrary and have no significance value.