In [1]:
import numpy as np

# 1D NumPy Array Slicing

In [7]:
array1 = np.array([1, 3, 5, 7, 8, 9, 2, 4, 6])

# slice array1 from index 2 to index 6 (exclusive)
print(array1[2:6])

# slice array1 from index 0 to index 8 (exclusive) with a step size of 2
print(array1[:8:2])

# slice array1 from index 3 up to the last element
print(array1[3:])

# items from start to end
print(array1[:])

[5 7 8 9]
[1 5 8 2]
[7 8 9 2 4 6]
[1 3 5 7 8 9 2 4 6]


# Modify Array Elements Using Slicing

In [10]:
array2 = np.array([2, 4, 6, 8, 10, 12])

# modify elements from index 3 onwards
array2[3:] = 20
print(array2)

# modify the first 3 elements
array2[:3] = 40
print(array2)

# modify elements from indices 2 to 5
array2[2:5] = 22
print(array2)

[ 2  4  6 20 20 20]
[40 40 40 20 20 20]
[40 40 22 22 22 20]


# 2D NumPy Array Slicing

In [12]:
array3 = np.array([[1, 3, 5, 7], [9, 11, 13, 15], [2, 4, 6, 8]])

# slice the array to get the first two rows and columns
print(array3[:2, :2])

# slice the array to get the last two rows and columns
print(array3[1:3, 2:4])

[[ 1  3]
 [ 9 11]]
[[13 15]
 [ 6  8]]
