In [1]:
import numpy as np

# Reshape 1D Array to 2D Array in NumPy

In [2]:
array1 = np.array([1, 3, 5, 7, 2, 4, 6, 8])

# reshape a 1D array into a 2D array with 2 rows and 4 columns
print(array1.reshape(2,4))

[[1 3 5 7]
 [2 4 6 8]]


# Reshape 1D Array to 3D Array in NumPy

In [3]:
array2 = np.array([1, 3, 5, 7, 2, 4, 6, 8])

print(array2.reshape(2,2,2))

[[[1 3]
  [5 7]]

 [[2 4]
  [6 8]]]
