In [5]:
import numpy as np

# NumPy Array Element-Wise Addition

In [6]:
first_array = np.array([1, 3, 5, 7])
second_array = np.array([2, 4, 6, 8])

# using the + operator
print(first_array + second_array)

# using the add() function
print(np.add(first_array,second_array))

[ 3  7 11 15]
[ 3  7 11 15]


# NumPy Array Element-Wise Subtraction

In [7]:
first_array = np.array([3, 9, 27, 81])
second_array = np.array([2, 4, 8, 16])

# using the - operator
print(first_array - second_array)

# using the subtract() function
print(np.subtract(first_array,second_array))

[ 1  5 19 65]
[ 1  5 19 65]


# NumPy Array Element-Wise Multiplication

In [8]:
first_array = np.array([1, 3, 5, 7])
second_array = np.array([2, 4, 6, 8])

# using the * operator
print(first_array * second_array)

# using the multiply() function
print(np.multiply(first_array,second_array))

[ 2 12 30 56]
[ 2 12 30 56]


# NumPy Array Element-Wise Division

In [9]:
first_array = np.array([1, 2, 3])
second_array = np.array([4, 5, 6])

# using the * operator
print(first_array / second_array)

# using the divide() function
print(np.divide(first_array,second_array))

[0.25 0.4  0.5 ]
[0.25 0.4  0.5 ]


# NumPy Array Element-Wise Exponentiation

In [11]:
array1 = np.array([1, 2, 3])

# using the ** operator
print(array1 ** 2)

# using the power() operator
print(np.power(array1,2))


[1 4 9]
[1 4 9]


# NumPy Array Element-Wise Modulus

In [12]:
first_array = np.array([9, 10, 20])
second_array = np.array([2, 5, 7])

# using the % operator
print(first_array % second_array)

# using the mod() function
print(np.mod(first_array,second_array))

[1 0 6]
[1 0 6]
