In [1]:
import numpy as np

# Trigonometric Functions

In [4]:
angles = np.array([0, 1, 2])

# compute the sine of the angles
sine_values = np.sin(angles)
print("Sine values:", sine_values)

# compute the inverse sine of the angles
inverse_sine = np.arcsin(angles)
print("Inverse Sine values:", inverse_sine)

angle =  1.57079633
# convert the angle to degrees
angle_degree = np.degrees(angle)
print("Angle in degrees:", angle_degree)

# convert the angle back to radians
angle_radian = np.radians(angle_degree)
print("Angle in radians (after conversion):", angle_radian)

Sine values: [0.         0.84147098 0.90929743]
Inverse Sine values: [0.         1.57079633        nan]
Angle in degrees: 90.0000001836389
Angle in radians (after conversion): 1.57079633


C:\Users\ASUS\AppData\Local\Temp\ipykernel_15684\2480440821.py:8: RuntimeWarning: invalid value encountered in arcsin
  inverse_sine = np.arcsin(angles)


# Rounding Functions

In [5]:
numbers = np.array([1.23456, 2.34567, 3.45678, 4.56789])

print(np.floor(numbers))
print(np.round(numbers))
print(np.ceil(numbers))

[1. 2. 3. 4.]
[1. 2. 3. 5.]
[2. 3. 4. 5.]
