In [1]:
import numpy as np

# Check Data Type of a NumPy Array

In [2]:
array1 = np.array([1,2,3])
print(array1.dtype)

# create an array of  integers
int_array = np.array([-3, -1, 0, 1])

# create an array of floating-point numbers
float_array = np.array([0.1, 0.2, 0.3])

# create an array of complex numbers
complex_array = np.array([1+2j, 2+3j, 3+4j])

print(int_array.dtype)  

print(float_array.dtype)  

print(complex_array.dtype)

int64
int64
float64
complex128


# Creating NumPy Arrays With a Defined Data Type

In [3]:
# create an array of 32-bit integers
array2 = np.array([1,2,3],dtype='int32')
print(array2,array2.dtype)

# create an array of 8-bit integers
array3 = np.array([1, 3, 7], dtype='int8')

# create an array of unsigned 16-bit integers
array4 = np.array([2, 4, 6], dtype='uint16')

# create an array of 32-bit floating-point numbers
array5 = np.array([1.2, 2.3, 3.4], dtype='float32')

# create an array of 64-bit complex numbers
array6 = np.array([1+2j, 2+3j, 3+4j], dtype='complex64')

# print the arrays and their data types
print(array3, array3.dtype)
print(array4, array4.dtype)
print(array5, array5.dtype)
print(array6, array6.dtype)

[1 2 3] int32
[1 3 7] int8
[2 4 6] uint16
[1.2 2.3 3.4] float32
[1.+2.j 2.+3.j 3.+4.j] complex64


# NumPy Type Conversion

In [4]:
int_array = np.array([1,3,5,7])

# convert data type of int_array to float
float_array = int_array.astype('float')

print(int_array, int_array.dtype)
print(float_array, float_array.dtype)


[1 3 5 7] int64
[1. 3. 5. 7.] float64
